apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-gateway-internal
  namespace: production
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
spec:
  gatewayClassName: envoy-gatewayclass
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: internal-proxy
  listeners:
    - name: rancher
      port: 443
      protocol: HTTPS
      hostname: rancher.akmalmaulana.net
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: rancher-akmalmaulana-net-tls
            kind: Secret
    - name: argocd
      port: 443
      protocol: HTTPS
      hostname: argocd.akmalmaulana.net
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: argocd-akmalmaulana-net-tls
            kind: Secret
    - name: prometheus
      port: 443
      protocol: HTTPS
      hostname: prom.akmalmaulana.net
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: prom-akmalmaulana-net-tls
            kind: Secret
