apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: production
  name: http-redirect-to-https
spec:
  parentRefs:
    - name: envoy-gateway
  hostnames:
    - "www.akmalmaulana.net"
    - "akmalmaulana.net"
    - "git.akmalmaulana.net"
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
