apiVersion: v1
kind: PersistentVolume
metadata:
  name: forgejo-pv-0
spec:
  storageClassName: local-vps
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  local:
    path: /mnt/kubernetes-volume/forgejo
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cerberus
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv-0
spec:
  storageClassName: local-vps
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  local:
    path: /mnt/kubernetes-volume/forgejo-db
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cerberus
