apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - ciss.letsencrypt-production.yaml
  - ciss.letsencrypt-staging.yaml
  - gtw.gateway-prod.yaml
  - gtwclass.envoy-gw.yaml
  - httproute.request-redirect.yaml
