apiVersion: v1
kind: PersistentVolume
metadata:
  name: forgejo-pv
spec:
  storageClassName: local-staging
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  local:
    path: /tmp/kubernetes-volume/forgejo
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pyroath-worker-node # change this to the name of the node with the disk

