apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  local:
    path: /tmp/kubernetes-volume/games/survival-server
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pyroath-worker-node # change this to the name of the node with the disk

