apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
spec:
  storageClassName: local-staging
  volumeName: database-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
