apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-action-data
spec:
  storageClassName: local-staging
  volumeName: forgejo-action-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
