apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
images:
  - name: git.akmalmaulana.net/akmalm007/blog
    newTag: placeholder
